### ISSUE TITLE
Not working since new TWiT website released

### ISSUE THREAD

**Issue by AlecEdworthy** [divingmule/plugin.video.twit#1]
Hello,

Since the new website was released I think the plugin has stopped working.  Are you able to fix this please?  Either way, thanks for making a useful app :)

Kind regards, Alec

**Comment by divingmule** [comment]
Working on it. Thanks for the heads up.

**Comment by AlecEdworthy** [comment]
No, thank you for working on it.  I was concerned you may no longer be supporting the app (I had to go digging around to work out how to add new streams to the app when TNSS was launched).  I managed to watch an episode over the weekend by AirPlaying it from my iPad but native playing is much better (AirPlaying an Internet stream is very hard on the battery).

Kind regards, Alec

**Comment by andrejstefanovski** [comment]
@divingmule let us in the community know if we can be of any help. even if it's just testing :)

**Comment by AlecEdworthy** [comment]
Absolutely, more than happy to help!

Alec

**Comment by divingmule** [comment]
Here is a test release. Let me know it anyone finds any issues.

https://github.com/divingmule/plugin.video.twit/raw/master/plugin.video.twit-2.0.9.zip

**Comment by AlecEdworthy** [comment]
Thanks @divingmule, I'll give it a whirl this evening.

A

**Comment by AlecEdworthy** [comment]
Seems OK.  Took me a few attempts to install it but got there in the end.  Live stream works, pre-recorded TNSS works.  Thank you!

Will this version of the plugin automatically detect and offer new shows?  For example when TNSS was launched I had to run a Python script on a separate computer to get it to generate a new show list and then copy that over onto the OpenElec box.

Kind regards, Alec

**Comment by TimeSearcher** [comment]
The 2.0.9 version works fine for me. Thanks!

**Comment by divingmule** [comment]
@AlecEdworthy 
Yes, all the shows are re-cached every six hours from the website.

**Comment by divingmule** [comment]
Thanks for the feedback!
