### ISSUE TITLE
[Floss Weekly] Showing only last 10 episodes in list

### ISSUE THREAD

**Issue by rprimus** [divingmule/plugin.video.twit#11]
Thu Jun 23 06:03:23 BST 2016

The summary list only shows the last 10 episodes (for most shows).  Other shows (Triangulation, The Tech Guy) show the last 20 episodes.

There is no longer a button to show "All previous episodes
![floss](https://cloud.githubusercontent.com/assets/278414/16292529/570f8a52-390a-11e6-86a2-c44c244a1641.jpg)
".

**Comment by divingmule** [comment]
Ahh... sorry for not responding. This version of the add-on is limited to what the RSS feed gives us. You can use the API addon or roll back to 2.1.3(if your using a recent version of Kodi) for a more full featured add-on. 
https://github.com/divingmule/plugin.video.twit/releases
