### ISSUE TITLE
Not Getting...

### ISSUE THREAD

**Issue by bonelifer** [divingmule/plugin.video.twit#13]
Not getting show ICONS or episode thumbnails for the last month or more.

**Comment by divingmule** [comment]
Thanks for bringing it to my attention. I hope to have time to look into it Monday or Tuesday though I don't recall having any issues myself the past few weeks.

Are you using the add-on from the official Kodi repo?

**Comment by divingmule** [comment]
New release for the API add-on. https://github.com/divingmule/plugin.video.twit/releases/download/V0.0.3/plugin.video.twit_api-0.0.3.zip
