### ISSUE TITLE
Playing Twit live fails when Youtube tries to show cookie dialog (Matrix)

### ISSUE THREAD

**Issue by robcast** [divingmule/plugin.video.twit#20]
Trying to play Twit live using Youtube fails for me (in Germany) with an error message.

It seems that Youtube presents the plugin with a cookie dialog that the code in `twit_live()` can not parse.

I think it worked before, maybe Youtube's dialog has changed.

I have not looked into Youtube's HTML code. Maybe there is a way to accept the cookie dialog programmatically.

**Comment by divingmule** [comment]
Hi, I'm not having any issues. Have you set up your API keys? > https://github.com/anxdpanic/plugin.video.youtube/wiki/Personal-API-Keys

**Comment by divingmule** [comment]
@robcast HI, sorry I misunderstood you. 
I was able to reproduce this issue with a German vpn. Not a great solution but I've decided, for now, to hard code the video id when parsing fails. Not sure but I don't think the id changes at least not very often, we'll see I guess.

**Comment by robcast** [comment]
The new version 2.3.1 works for me 👍 Thanks @divingmule !

I like your compromise of hardcoding the video id. If that doesn't work it's still possible to add the complication of trying to simulate clicking the "accept" button.

**Comment by robcast** [comment]
Sadly the hardcoded video id stopped working for me. 

So I went back to my original plan to treat the resulting page as cookie consent page and submit the form programmatically: #21 (I tried to make the code look like the rest, feel free to clean it)

It works for me(tm) 😁

**Comment by robcast** [comment]
closed in #21 (for now...)
