### ISSUE TITLE
Is 'Latest'-only stream possible under new API?

### ISSUE THREAD

**Issue by andrejstefanovski** [divingmule/plugin.video.twit#3]
I noticed the change from 'most recent' section to 'featured @ twit.tv' w/ v2.0.9+ and I'm wondering if that's due to the changes in the backend of if a 'latest' / 'most recent' section at the top is still possible.

I primarily use my RPi to watch twit live when I happen to have a day I'm working from home, but from time to time I want to scan through the most recent shows and the new 'featured' filter is adding complexity and confusion. I've clicked many times on a show title only to realize as it's loading that it's a [News] or some other edited piece rather than the whole show.

Are there API issues with say, having a purely whole-show "latest section" below 'featured @ twit.tv' ? Also, is a manual update of the show feed possible? 6 hours is a bit long especially if an update happens right before a new episode of a late show (i.e. all about android). Are they limiting hits on the API on their end?

Thanks for all the great work on getting it updated for the new Twit backend :)

**Comment by divingmule** [comment]
The current 2.1.0 version still uses the website for data. With the website change there was no longer a recent shows feed, so... 'featured @ twit.tv' list the shows from the twit.tv homepage. I noticed recently "All TWiT Shows" show was added to the website but they haven't added any episodes yet. If they get episodes added the add-on should pick it up. If that doesn't work out I may write a scraper to get the data from the RSS feed.

The six hour cache is only for the list of available shows, not episodes. The only delay is when a show is added or removed.

The restrictions with the API are ridiculous, five calls per minute, making it impractical(in my opinion) for a project like this. That being said I have written an add-on that uses the API where the user can add their own API keys. https://github.com/divingmule/plugin.video.twit/tree/api

**Comment by andrejstefanovski** [comment]
Ah! It all makes sense now.

Regarding the API, I thought as much when I heard Leo mention how they're making everyone register for one so they can pull them if someone was overdoing it. It made me think of the Android developer that put in place a way for us to put in our own Twitter API Keys so every individual became a 'client' capable of requesting tokens. I was going to offer that as a possible solution to a rate-limited API problem but it seems you are already far ahead of me :)

Thanks again for all the hard work, I'll be on the lookout for more on that project

**Comment by sjefen6** [comment]
Why not just request an api key and include it? Maybe base64 it for obfuscation or something but I don't think the keys must be kept super secret. Abuse is somewhat twits problem, and all applications will have to include it. The fact that twits website does not lets users read the key is more of an exception than what must be normal for thin kind of API. But with a read only api the chance of abuse is kind of limited...

**Comment by divingmule** [comment]
@sjefen6 I just pushed version 0.0.2 with default keys, we'll see how it goes.
