### ISSUE TITLE
Plugin no longer working on Kodi on Raspberry Pi OpenELEC

### ISSUE THREAD

**Issue by avoura** [divingmule/plugin.video.twit#4]
This used to work okay as a plugin to view Twit.tv netcasts, but now I get an error. Using it on latest Kodi on Raspberry Pi OpenELEC. I was able to view part of Log file and it showed an error in the python code.
It no longer works and cannot access any Twit.tv netcasts. I can see a list of shows, but not a list of episodes.

**Comment by divingmule** [comment]
Hi, this issue was resolved in the latest version 2.1.1.
