### ISSUE TITLE
plugin fails when retrieving video list

### ISSUE THREAD

**Issue by Erroneous1** [divingmule/plugin.video.twit#6]
> 07:46:31 T:139713566451456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.TypeError'>
>                                             Error Contents: object of type 'NoneType' has no len()
>                                             Traceback (most recent call last):
>                                               File "/home/data/.kodi/addons/plugin.video.twit/default.py", line 373, in <module>
>                                                 display_main()
>                                               File "/home/data/.kodi/addons/plugin.video.twit/default.py", line 96, in display_main
>                                                 display_shows('active')
>                                               File "/home/data/.kodi/addons/plugin.video.twit/default.py", line 75, in display_shows
>                                                 shows = cache.cacheFunction(shows_cache)
>                                               File "/home/data/.kodi/addons/script.common.plugin.cache/lib/StorageServer.py", line 570, in cacheFunction
>                                                 ret_val = funct(*args)
>                                               File "/home/data/.kodi/addons/plugin.video.twit/default.py", line 66, in shows_cache
>                                                 'active': parse_shows_to_list(base_url + '/shows?shows_active=1'),
>                                               File "/home/data/.kodi/addons/plugin.video.twit/default.py", line 56, in parse_shows_to_list
>                                                 soup = BeautifulSoup(make_request(shows_url), 'html.parser')
>                                               File "/home/data/.kodi/addons/script.module.beautifulsoup4/lib/bs4/**init**.py", line 162, in **init**
>                                                 elif len(markup) <= 256:
>                                             TypeError: object of type 'NoneType' has no len()
>                                             -->End of Python script error report<--
> 07:46:31 T:139715333724288   ERROR: GetDirectory - Error getting plugin://plugin.video.twit/?content_type=video
> 07:46:31 T:139715333724288   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.twit/?content_type=video) failed

Looks like a check needs to be performed to make sure that the url actually returned data.

**Comment by divingmule** [comment]
Yeah, wouldn't be a bad idea.
